### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Airon90** [socioboard/socioboard-core#11]
Is it possible to translate socioboard? I'd like to translate it into Italian and Esperanto

**Comment by Airon90** [comment]
You closed this issue without an update. Why?

**Comment by socioboard** [comment]
Translations have been included in release 2.0, hence I marked this as closed. Let me know if you are facing any issues else I will keep it closed for now.

**Comment by Airon90** [comment]
Ehm, in my first post I asked you how to translate Socioboard. You said that you're going to "integrate" translations and now you closed the issue saying that translations have been included in 2.0
I'm confused. Where can I help in translation? I'd like to translate into Italian and Esperanto or check translations if they are already present.
Thank you very much!
