### ISSUE TITLE
problem with DataServices and  DataScheduler

### ISSUE THREAD

**Issue by Sak1s** [socioboard/socioboard-core#18]
I can not make any scheduled post  and also resync  my social data.

The output of the above executives :
"No active record in Database."

**Comment by Sak1s** [comment]
any help ?

**Comment by socioboard** [comment]
Please check the latest build. It's fixed in that

**Comment by Sak1s** [comment]
In this release there are many files missing and i cannot build the project.

**Comment by socioboard** [comment]
ok, let me check and update shortly

**Comment by socioboard** [comment]
hi
could you please download this release
https://github.com/socioboard/socioboard/releases/tag/v2.0.15
Regards

**Comment by socioboard** [comment]
This issue has been fixed, am marking it closed now.
