### ISSUE TITLE
Class1.cs could not be found

### ISSUE THREAD

**Issue by bobstermyang** [socioboard/socioboard-core#20]
I'm getting a few errors when i try to compile the project on visual studio:

I've attached a photo with the error.
![capture](https://cloud.githubusercontent.com/assets/5743321/7865452/1e20104a-0526-11e5-82ca-2c7775583d46.PNG)

**Comment by socioboard** [comment]
please find the new release https://github.com/socioboard/socioboard-core/releases/tag/v2.0.21
it's solved there

Socioboard Support

**Comment by bobstermyang** [comment]
cool, that has been solved. I'm still getting the

Source file 'Web References\Api.LinkedinMessage\Reference.cs' could not be found

**Comment by socioboard** [comment]
you need to update/create new web references from your local API project. And rebuild. 
follow these steps
http://i.imgur.com/03bdqmt.png?1
http://i.imgur.com/dDaf9QG.png?1
Also updated in ReadMe document
Socioboard Support
