### ISSUE TITLE
Problem with GlobusMailLib

### ISSUE THREAD

**Issue by iwxfer** [socioboard/socioboard-core#21]
I can't compilae solution, Visual Studio 2013 with Windows 8
![2015-09-13 10-49-48 socioboard - microsoft visual studio](https://cloud.githubusercontent.com/assets/642371/9837471/53c6bef4-5a05-11e5-9868-7f56bb5356f9.png)

**Comment by thenna** [comment]
Hi,
In the error log, go to item 24 "The name SMTP does not exist". just press ctrl+. you will be asked to refer the sendgrid, just hit all the errors will go off. Then you will get one error as GlobusMailLib.dll was not found. Now rebuild the solution you will be good to go..!

Thanks,
Thenna R


Date: Sun, 13 Sep 2015 08:51:46 -0700

**Comment by iwxfer** [comment]
ctrl+ has any effect, any other suggestion?

**Comment by thenna** [comment]
its ctrl+. (dot) or jut highlight the error you will get Roslyn suggestion in case if you don't have a re-sharper. 

Thanks,
Thenna R


Date: Mon, 14 Sep 2015 11:15:44 -0700

**Comment by iwxfer** [comment]
None of suggestions work, maybe because I am using Visual Studio Express.

**Comment by thenna** [comment]
here you go.. use this DLL...

Thanks,
Thenna R


Date: Mon, 14 Sep 2015 12:26:12 -0700

**Comment by iwxfer** [comment]
There is no DLL, I guess github doesn't support to attach files in the issues. I am getting other errors related with Excel Application. I think it would be a good idea to break the whole code in small modules or libs, so it turn more usable. For example, we can just have a project for API, if you can provide some guidelines so extract just the API then we can join with a Web, desktop or mobile apps.

**Comment by sumitglobussoft** [comment]
The api is a separate project already. The Socioboard project is the main web app. The code follows service oriented architecture already.

Sumit

**Comment by socioboard** [comment]
The api is a separate project already. The Socioboard project is the main web app. The code follows service oriented architecture already.

Sumit

**Comment by socioboard** [comment]
Regarding the libraries, there is a libs folder, all libraries are placed under that. 

Please make sure you reference the once which are giving missing ref error.

**Comment by iwxfer** [comment]
Let me explain better about separating project, I was talking about using different git repositories for every project, so if somebody needs just to work on some module/library, just work with that, and use the compiled versions of other things. 

I am not .Net expert, maybe this isn't possible with .Net. I am more familiar with Java, and it is common to create different source repos for libraries (JARs in Java and I guess dll in .Net).

**Comment by socioboard** [comment]
That's correct, a jar in java is equivalent to a DLL in .NET. Each .NET project in the solution can be compiled and worked upon separately and when compiled outputs a DLL which is being used in other projects. You can fork the whole repo, commit your changes and send me a pull request. I will verify and if its fine I shall merge it in main repo.

Creating separate repos for each DLL doesn't make sense and it could become a maintenance nightmare for us.

Sumit
