### ISSUE TITLE
where can i find copy of mongoDB used

### ISSUE THREAD

**Issue by prog-moh** [socioboard/socioboard-core#24]
where can i find copy of mongoDB used

**Comment by fsarcos** [comment]
I was wondering the same, twitter use mongoDB in all the solution nobody said something about this

**Comment by socioboard** [comment]
HI, 
The database of the mongoDB is as same as the classes there is no different schema . i.e (https://github.com/socioboard/socioboard-core/tree/master/SocioBoard/Domain.Socioboard/MongoDomain) . here is an example of JSON for twitter message  which can help you  figuring out 
{
    "_id" : ObjectId("56546d52df0a201a34b52d1d"),
    "Id" : {
        "Timestamp" : 1.44837e+009,
        "Machine" : 1.46171e+007,
        "Pid" : 6708,
        "Increment" : 1.18736e+007,
        "CreationTime" : "/Date(1448373586000)/"
    },
    "TwitterMsg" : "hii @lovely35667  how are u ?",
    "MessageDate" : "2015/11/20 17:28:02",
    "ProfileId" : "2604984842",
    "FromId" : "2604984842",
    "FromName" : null,
    "FromProfileUrl" : "http://pbs.twimg.com/profile_images/616565946249932800/qyJJP31J_normal.jpg",
    "ScreenName" : "lovely35667",
    "MessageId" : "667673250625773568",
    "Type" : "twt_mentions",
    "InReplyToStatusUserId" : "",
    "SourceUrl" : "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>",
    "FromScreenName" : "lovely35667",
    "ReadStatus" : 0,
    "IsArchived" : 0,
    "Positive" : 0.9957030000000000,
    "Negative" : 0.0042965900000000,
    "ProfileType" : "twitter"
}
