### ISSUE TITLE
Problem registration form & access admin panel

### ISSUE THREAD

**Issue by electronic-city** [socioboard/socioboard-core#25]
Hi admin

I am currently using Windows Server 2012 R2 & MySQL 5.7 as well
I am having problem about registration after i setup socioboard.
And also, i followed this instruction at 
http://wiki.socioboard.com/index.php/Socioboard_Installation_Wiki
or
http://wiki.socioboard.com/images/9/98/Socioboard_Installation_Guide_2.0.pdf

When i go to link at http://example.com/Index/Registration and after i filling form, the error message appear say "failure'
What could be this problem :( ?

Here, I provide a screenshot error:
http://i67.tinypic.com/33nf0b5.png

And also, how do i access admin dashboard? (I mean, the link website name for accessing admin dashboard)

I am new here for using your Socioboard.

Please help :(

Thanks

**Comment by socioboard** [comment]
Hello, 
Well, the details you provided here are limited. A more detailed explanation would have been better for us to debug the issue. 
Here the problem may be with the database connectivity, please check the credentials of your database in "hibernate.cfg.xml".
If everything is fine, then please check the file "log.txt", you may find the issue there. If this did not solve your problem, please contact support@socioboard.com or contact us on Skype-ID : socioboard.support

 
For accessing the admin panel, the flow goes like this
1. Register as a normal user in the registration page.
2. Once the user is successfully registered, in your database open "user" table 
   and change the corresponding user's "UserType" field to "SuperAdmin".
3. Next time you log-in with your credentials, you will be logged in as admin.

**Comment by electronic-city** [comment]
Hi,
Thanks for reply my issue before

Well, if you ask me about "log.txt" in C:\inetpub\wwwroot\socioboard\Socioboard\log.txt (not sure if this right location or not), here i provide it for you:
[log.txt](https://github.com/socioboard/socioboard-core/files/65162/log.txt)

And about connectivity MySQL, i think yes, i had problem about setting config file
I am not sure if i edit this file name "hibernate.cfg.xml" at C:\inetpub\wwwroot\socioboard\SocioboardAPI\hibernate.cfg.xml can be effect or not, but it looks not effective for me after i run this application.

Should i modify file name "Web.config" between C:\inetpub\wwwroot\socioboard\Socioboard and C:\inetpub\wwwroot\socioboard\SocioboardAPI beside hibernate.cfg.xml?

Sorry, i am new for using Windows Server 2012 for the first time :(

Maybe i should email your email address or chatting through Skype that your provide me

Please help

Thanks

**Comment by Vipul23** [comment]
I am facing the same issue. Getting failure after registering to the new user form. Can anyone help?

**Comment by socioboard** [comment]
Hello, 
Well, can you clear log (Socioboard/SocioboardApi/log.txt), run your application and provide us the log.txt file so that we can help you better.

**Comment by Vipul23** [comment]
Yes, I am uploading it here.
[log.txt](https://github.com/socioboard/socioboard-core/files/298996/log.txt)

**Comment by nQaze** [comment]
I am also facing the same issue. Mine log file shows the following:
ERROR2016-09-08 05:04:49 Class:Socioboard.Controllers.IndexController Method:Signup Line #: 245  – Register

**Comment by nkdksk** [comment]
We have the problem ERROR2016-09-08 05:04:49 Class:Socioboard.Controllers.IndexController Method:Signup Line #: 333 – Register we are behind a proxy, we solve the problem running socioboard in a machine outside, the problem can be port permissions

**Comment by socioboard** [comment]
This project is outdated and not supported as of now now please download the new version from - https://github.com/socioboard/Socioboard-Core-3.0

**Comment by carlosbarr** [comment]
I update the version of socioboard but I get the following error when making "rebuild" in Visual studio

> Cannot infer TargetFrameworkIdentifier and/or TargetFrameworkVersion from TargetFramework='dnx46'. They must be specified explicitly

![image](https://cloud.githubusercontent.com/assets/26493914/24065418/d0f32bfc-0b38-11e7-826b-efa9a34e45a1.png)
