### ISSUE TITLE
Can't Add Facebook account

### ISSUE THREAD

**Issue by imadbakir** [socioboard/socioboard-core#28]
Hi, 
I'm trying to add facebook account to the dashboard, 
I added the APP ID and the secret and done all configuration and redirect URI is /facebookManager/Facebook, which points as it seems to the correct controller and correct method, 
though nothing happens, and the account is not being added to the dashboard, nor appears in the DB, 
the code is failing somewhere or something.

**Comment by socioboard** [comment]
Try to first setup the app on localhost and debug it using visual studio to make sure everything has been setup correctly. Once its working fine on local, make the appropriate changes in config file and push to server.
