### ISSUE TITLE
where is this extension method "CalculateTimeDiff"

### ISSUE THREAD

**Issue by prog-moh** [socioboard/socioboard-core#29]
where is this extension method CalculateTimeDiff
called in this view
https://github.com/socioboard/socioboard-core/blob/416f6d0786fc1c5cbeb717a92ffe5824340f2fec/SocioBoard/Socioboard/Themes/Socioboard/Views/Feeds/_InstagramPartial.cshtml

**Comment by socioboard** [comment]
Hi, 
  Here is the class which has CalculateTimeDiff method https://github.com/socioboard/socioboard-core/blob/master/SocioBoard/Socioboard/Helper/DateExtension.cs

**Comment by socioboard** [comment]
Closing this as fixed.
