### ISSUE TITLE
adding/connecting  social profiles

### ISSUE THREAD

**Issue by scharada** [socioboard/socioboard-core#30]
non of the profiles work ... it looks like few of them are even outdated ...

here are few results for adding profiles in :
LinkedIn:

![li](https://cloud.githubusercontent.com/assets/1780858/13184175/abbb023e-d73a-11e5-89d7-004a009611eb.PNG)

Facebook :
![fb](https://cloud.githubusercontent.com/assets/1780858/13184191/bf06366a-d73a-11e5-9ee8-4da9e5ba5a24.PNG)

YouTube:
![yt](https://cloud.githubusercontent.com/assets/1780858/13184195/c8869a04-d73a-11e5-9ed1-fcb185c47b10.PNG)

while tumbler, Instagram and Twitter do absolutely nothing.

any help ?

thank you.

**Comment by socioboard** [comment]
You have not setup the application api keys correctly. Check out the live application at - www.socioboard.com , everything works fine!
