### ISSUE TITLE
r_network permission in Linkedin

### ISSUE THREAD

**Issue by adnanzaman** [socioboard/socioboard-core#33]
https://api.linkedin.com/v1/people/~/network/updates?type=CONN&count=50&start=0 when i call this then error occur Access denied. LinkedIn deprecated this permission r_network.can you tell me alternative way to get this and when you upload new version of socioboard.

**Comment by socioboard** [comment]
We are updating the linkedin library to deprecate this call. Please check out the upcoming May 15th release.
