### ISSUE TITLE
Unable to make schedule & other issues.

### ISSUE THREAD

**Issue by swativerma1980** [socioboard/socioboard-core#34]
I have configured this app on my localhost.
There were several issued i.e
1.I was unable to schedule message also documentation was not so good.
2.I was unable add my Google plus account there was no parameter given in config file.
3.I was unable to find the detail to configure Admin Panel or super user who will manage the other users in the system.

**Comment by socioboard** [comment]
Please read the detailed documentation provided at wiki.socioboard.com
