### ISSUE TITLE
App Crash when Click on UserGroup

### ISSUE THREAD

**Issue by AzeePak** [socioboard/socioboard-core#42]
Getting this excetion when i click on group

http://localhost:9821/UserGroup/Index

Description:
{"Cannot convert type 'System.Collections.Generic.List<Domain.Socioboard.Domain.Groupmembers>' to 'System.Collections.Generic.List<Domain.Socioboard.Domain.Team>'"}

Facebook profile is attached. but when click on groups this exception appers. 
Screenshot  is attached!
![screenshot 179](https://cloud.githubusercontent.com/assets/25144787/21972809/132ec8da-dbde-11e6-985c-a51e144cfb06.png)
![screenshot 178](https://cloud.githubusercontent.com/assets/25144787/21972831/36d8fbde-dbde-11e6-8218-1a559a543b23.png)
![screenshot 180](https://cloud.githubusercontent.com/assets/25144787/21972839/3cad55d2-dbde-11e6-8b9e-3e0b2f62ecb3.png)
![screenshot 182](https://cloud.githubusercontent.com/assets/25144787/21972850/48c961d0-dbde-11e6-9616-52b988a39412.png)
![screenshot 181](https://cloud.githubusercontent.com/assets/25144787/21972857/54076416-dbde-11e6-927b-6572bd3de585.png)

**Comment by socioboard** [comment]
Hi AzeePak,
                  You are using older code you should download newer code from below mention link
https://github.com/socioboard/Socioboard-Core-3.0

**Comment by AzeePak** [comment]
I am using old code, Now i will try the Core version! Thanks

**Comment by AzeePak** [comment]
Thnaks Syumit!
