### ISSUE TITLE
Could not load file or assembly 'ChilkatDotNet2' or one of its dependencies. 

### ISSUE THREAD

**Issue by maksudcs** [socioboard/socioboard-core#43]
Could not load file or assembly 'ChilkatDotNet2' or one of its dependencies. An attempt was made to load a program with an incorrect format.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.BadImageFormatException: Could not load file or assembly 'ChilkatDotNet2' or one of its dependencies. An attempt was made to load a program with an incorrect format.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Assembly Load Trace: The following information can be helpful to determine why the assembly 'ChilkatDotNet2' could not be loaded.

=== Pre-bind state information ===
LOG: DisplayName = ChilkatDotNet2
 (Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: ChilkatDotNet2 | Domain ID: 3
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
LOG: Appbase = file:///E:/Working Project/Documents/Fiverr/#FO6A99D42FA3------cadygb/socioboard-core-master/socioboard-core-master/SocioBoard/Socioboard/
LOG: Initial PrivatePath = E:\Working Project\Documents\Fiverr\#FO6A99D42FA3------cadygb\socioboard-core-master\socioboard-core-master\SocioBoard\Socioboard\bin
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: E:\Working Project\Documents\Fiverr\#FO6A99D42FA3------cadygb\socioboard-core-master\socioboard-core-master\SocioBoard\Socioboard\web.config
LOG: Using host configuration file: C:\Users\bITS\Documents\IISExpress\config\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Users/bITS/AppData/Local/Temp/Temporary ASP.NET Files/root/81251bca/65888991/ChilkatDotNet2.DLL.
LOG: Attempting download of new URL file:///C:/Users/bITS/AppData/Local/Temp/Temporary ASP.NET Files/root/81251bca/65888991/ChilkatDotNet2/ChilkatDotNet2.DLL.
LOG: Attempting download of new URL file:///E:/Working Project/Documents/Fiverr/#FO6A99D42FA3------cadygb/socioboard-core-master/socioboard-core-master/SocioBoard/Socioboard/bin/ChilkatDotNet2.DLL.
ERR: Failed to complete setup of assembly (hr = 0x8007000b). Probing terminated.

Stack Trace: 

[BadImageFormatException: Could not load file or assembly 'ChilkatDotNet2' or one of its dependencies. An attempt was made to load a program with an incorrect format.]
   System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0
   System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +234
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +108
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +25
   System.Reflection.Assembly.Load(String assemblyString) +34
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +49

[ConfigurationErrorsException: Could not load file or assembly 'ChilkatDotNet2' or one of its dependencies. An attempt was made to load a program with an incorrect format.]
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +772
   System.Web.Configuration.CompilationSection.LoadAllAssembliesFromAppDomainBinDirectory() +259
   System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai) +163
   System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig) +230
   System.Web.Compilation.BuildManager.GetPreStartInitMethodsFromReferencedAssemblies() +76
   System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +139
   System.Web.Compilation.BuildManager.ExecutePreAppStart() +176
   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +882

[HttpException (0x80004005): Could not load file or assembly 'ChilkatDotNet2' or one of its dependencies. An attempt was made to load a program with an incorrect format.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +579
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +112
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +712

**Comment by socioboard** [comment]
Hi maskudcs,
Are you using old version socioboard2.0
we have alreaday updated the new version i.e socioboard3.0
please use that.
https://github.com/socioboard/Socioboard-Core-3.0
